AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS PostgreSQL Stack for Shield Your Assets API'

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: shield-assets-prod
  
  DBMasterUsername:
    Description: Database master username
    Type: String
    Default: medicaid_admin
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters or underscore
  
  DBMasterPassword:
    Description: Database master password
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 128
    AllowedPattern: '[a-zA-Z0-9!@#$%^&*()_+=]*'
    ConstraintDescription: Must contain at least 8 characters

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${EnvironmentName}-db-subnet-group
      DBSubnetGroupDescription: Subnet group for Shield Assets RDS
      SubnetIds:
        - !ImportValue 
          Fn::Sub: ${EnvironmentName}-PRIVATE-SUBNET-1
        - !ImportValue 
          Fn::Sub: ${EnvironmentName}-PRIVATE-SUBNET-2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-db-subnet-group

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-rds-sg
      GroupDescription: Security group for Shield Assets RDS
      VpcId: !ImportValue
        Fn::Sub: ${EnvironmentName}-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ECSSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-rds-sg

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-ecs-sg
      GroupDescription: Security group for Shield Assets ECS tasks
      VpcId: !ImportValue
        Fn::Sub: ${EnvironmentName}-VPC-ID
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ecs-sg

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: !Sub ${EnvironmentName}-pg15
      Description: Custom parameter group for Shield Assets
      Family: postgres15
      Parameters:
        shared_preload_libraries: pg_stat_statements
        log_statement: all
        log_duration: 'on'
        log_min_duration_statement: 1000

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-db
      DBInstanceClass: db.t3.small
      Engine: postgres
      EngineVersion: '15.8'
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      AllocatedStorage: 100
      StorageType: gp3
      StorageEncrypted: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBParameterGroupName: !Ref DBParameterGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "03:00-04:00"
      PreferredMaintenanceWindow: "sun:04:00-sun:05:00"
      MultiAZ: true
      PubliclyAccessible: false
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      DeletionProtection: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-db

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/rds/credentials
      Description: RDS credentials for Shield Assets API
      SecretString: !Sub |
        {
          "username": "${DBMasterUsername}",
          "password": "${DBMasterPassword}",
          "engine": "postgres",
          "host": "${DBInstance.Endpoint.Address}",
          "port": ${DBInstance.Endpoint.Port},
          "dbname": "medicaid_planning"
        }
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-rds-credentials

Outputs:
  DBEndpoint:
    Description: Database endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}-DB-ENDPOINT

  DBPort:
    Description: Database port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub ${EnvironmentName}-DB-PORT

  DBSecretArn:
    Description: Database credentials secret ARN
    Value: !Ref DBSecret
    Export:
      Name: !Sub ${EnvironmentName}-DB-SECRET-ARN

  ECSSecurityGroupId:
    Description: ECS Security Group ID
    Value: !Ref ECSSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-ECS-SG-ID

  DBSecurityGroupId:
    Description: RDS Security Group ID
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-RDS-SG-ID